name: deploy prod
on: [ push ]
jobs:
    build_test_deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Configure
                uses: jsdaniell/create-json@1.1.2
                with:
                    name: config.json
                    json: ${{ secrets.CONFIG_SPA_PROD_JSON }}
                    dir: config/
            -   uses: actions/cache@v2
                id: yarn-build-cache
                with:
                    path: |
                        node_modules
                        ~/.cache/Cypress
                        public/build
                    key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-node_modules-build-
            -   name: Launch web server for tests
                run: |
                    docker run -d --rm -p 80:80 -v $PWD/public:/usr/local/apache2/htdocs/:ro httpd:2.4
            -   name: Build SPA and Launch cypress
                uses: cypress-io/github-action@v2
                env:
                    CYPRESS_baseUrl: 'http://localhost'
                with:
#                    runTests: false
                    browser: chrome
                    wait-on: 'http://localhost'
                    build: yarn build
            -   name: Clean config
                run: rm -f config/config.json
            -   name: Archive cypress videos
                uses: actions/upload-artifact@v2
                with:
                    name: cypress-tests-videos
                    path: |
                        cypress/videos
            -   name: Deploy to AWS S3 prod
                uses: awact/s3-action@master
                if: ${{ startsWith(github.ref, 'refs/tags/v') }}
                env:
                    SOURCE_DIR: './public'
                    AWS_REGION: eu-west-1
                    AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_PROD }}
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
